### PR TITLE
Update grunt options and other updates

### PR DESCRIPTION
**Pull request by bahmutov**
Hi,
I upgraded the dependencies, added option to not fail if there are no files, tested detection. Would love to use these features in our projects. I upgraded version to 0.2.0, so if it could be published that would be great.

### CODE REVIEW

**Comment by jakub-g** [comment]
Hi, thx for the PR, I will have a look in the coming days!

**Comment by jakub-g** [comment]
Looks good :+1: I'll merge it tomorrow

**Comment by jakub-g** [comment]
merged & pushed 0.2.0 to npm, thanks for the PR!

**Comment by bahmutov** [comment]
Thanks a lot!

**Pull request merged**
